global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "go-backend"
    scrape_interval: 5s
    scrape_timeout: 4s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          service: "tinyurl-api"
          environment: "development"