name: Backend CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'go-server/**'
      - '.github/workflows/backend.yml'
  push:
    branches: [ main ]
    paths:
      - 'go-server/**'
      - '.github/workflows/backend.yml'

jobs:
  lint_backend:
    name: Backend – Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: go-server

  build_backend:
    name: Backend – Build
    runs-on: ubuntu-latest
    needs: lint_backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          cd go-server
          go build ./...

  test_backend:
    name: Backend – Tests
    runs-on: ubuntu-latest
    needs: build_backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test Suite
        run: |
          cd go-server
          go test ./... -cover

  deploy_backend:
    name: Backend – Deploy to AWS ECS
    runs-on: ubuntu-latest
    needs: test_backend
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          cd go-server
          docker build --platform linux/x86_64 -t tiny-url:latest .

      - name: Tag Image
        run: |
          docker tag tiny-url:latest 173941740239.dkr.ecr.us-east-1.amazonaws.com/tiny-url:latest

      - name: Push Image
        run: |
          docker push 173941740239.dkr.ecr.us-east-1.amazonaws.com/tiny-url:latest

      - name: ECS Deployment
        run: |
          aws ecs update-service \
            --cluster tiny-url-cluster \
            --service tiny-url-task-service-mbc61hhc \
            --force-new-deployment
