name: Backend CI/CD

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  lint_backend:
    name: Lint (backend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: go-server

  build_backend:
    name: Build (backend)
    runs-on: ubuntu-latest
    needs: lint_backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          cd go-server
          go build ./...

  test_backend:
    name: Tests (backend)
    runs-on: ubuntu-latest
    needs: build_backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Execute Test Suite
        run: |
          cd go-server
          go test ./... -cover

  deploy_backend:
    name: Deploy (backend)
    runs-on: ubuntu-latest
    needs: test_backend
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          cd go-server
          docker build --platform linux/x86_64 -t tiny-url:latest .

      - name: Tag Image
        run: |
          docker tag tiny-url:latest 173941740239.dkr.ecr.us-east-1.amazonaws.com/tiny-url:latest

      - name: Push Image
        run: |
          docker push 173941740239.dkr.ecr.us-east-1.amazonaws.com/tiny-url:latest

      - name: Deploy ECS Service
        run: |
          SERVICE_NAME="tiny-url-backend-v1"
          CLUSTER="tiny-url-cluster"

          TASK_DEF_ARN=$(aws ecs describe-task-definition \
            --task-definition tiny-url-task \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          if aws ecs describe-services \
            --cluster $CLUSTER \
            --services $SERVICE_NAME \
            --query "services[0].status" \
            --output text 2>/dev/null | grep -q ACTIVE; then

            echo "Service exists. Updating..."
            aws ecs update-service \
              --cluster $CLUSTER \
              --service $SERVICE_NAME \
              --task-definition $TASK_DEF_ARN \
              --force-new-deployment

          else

            echo "Service does not exist. Creating..."
            aws ecs create-service \
              --cluster $CLUSTER \
              --service-name $SERVICE_NAME \
              --task-definition $TASK_DEF_ARN \
              --desired-count 1 \
              --launch-type FARGATE \
              --platform-version LATEST \
              --load-balancers "targetGroupArn=arn:aws:elasticloadbalancing:us-east-1:173941740239:targetgroup/tiny-url-backend-tg/e293f4dbc5fb3348,containerName=tiny-url,containerPort=8080" \
              --network-configuration "awsvpcConfiguration={subnets=[subnet-0e74fd56f00fc99bb,subnet-06de462555d65e7ed,subnet-0d840e839344ad29a,subnet-0c11dd7b6b9e381ab,subnet-0bd2651cfac4d5c07,subnet-0321f89418c8e0871],securityGroups=[sg-03912536dade39a55],assignPublicIp=ENABLED}" \
              --health-check-grace-period-seconds 60
          fi

