name: CI/CD Go API (ECR + ECS)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        working-directory: go-server
        run: go mod download

      # - name: Run tests
      #   working-directory: go-server
      #   run: go test ./... -cover


  cd:
    name: Build & Deploy to AWS
    runs-on: ubuntu-latest
    needs: ci   # só executa depois do CI ter passado

    if: github.ref == 'refs/heads/main'   # só roda no merge na main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: go-server
        run: |
          docker build --platform linux/x86_64 -t tiny-url .

      - name: Tag image
        run: |
          docker tag \
            tiny-url:latest \
            173941740239.dkr.ecr.us-east-1.amazonaws.com/tiny-url:latest

      - name: Push image
        run: |
          docker push 173941740239.dkr.ecr.us-east-1.amazonaws.com/tiny-url:latest

      - name: Render new ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task.json     # seu arquivo local
          container-name: tiny-url
          image: 173941740239.dkr.ecr.us-east-1.amazonaws.com/tiny-url:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: tiny-url-service
          cluster: tiny-url-cluster
          wait-for-service-stability: true
