name: Frontend CI/CD

on:
  pull_request:
    branches: [ main ]
    
  push:
    branches: [ main ]

jobs:
  lint_frontend:
    name: Frontend – Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          cd angular-app
          npm ci

      - name: Angular Lint
        run: |
          cd angular-app
          npm run lint --if-present

  build_frontend:
    name: Frontend – Build
    runs-on: ubuntu-latest
    needs: lint_frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Angular App
        run: |
          cd angular-app
          npm ci
          npm run build --if-present

  deploy_frontend:
    name: Frontend – Deploy to AWS ECS
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build_frontend

    steps:
      - uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          cd angular-app
          docker build --platform linux/x86_64 -t tiny-url-frontend:latest .

      - name: Tag Image
        run: |
          docker tag tiny-url-frontend:latest 173941740239.dkr.ecr.us-east-1.amazonaws.com/tiny-url-frontend:latest

      - name: Push Image
        run: |
          docker push 173941740239.dkr.ecr.us-east-1.amazonaws.com/tiny-url-frontend:latest

      - name: ECS Deployment
        run: |
          aws ecs update-service \
            --cluster tiny-url-cluster \
            --service tiny-url-frontend-task-service-lxfb9ner \
            --force-new-deployment
